apiVersion: v1
kind: Service
metadata:
  name: backend-hotspots-ml-service
  labels:
    app: hotspots
spec:
  selector:
    app: backend-ml-hotspots-app
  ports:
    - port: 8080
      protocol: TCP
  type: LoadBalancer