version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.1.0
  gcr: circleci/gcp-gcr@0.6.1

jobs:
  build_and_test:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/rkshkmr800/hotspots
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go build ./...
      - run: go test ./...

  build_and_push_container:
    description: Build the image and then push the container to gcr
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          dockerfile: Backend.Dockerfile
          path: ./docker/
          image:  hotspots-backend-gke 
          tag:  v1
      - gcr/push-image:
          image:  hotspots-backend-gke
          tag:  v1
      
workflows:
  continuous_integration:
    jobs:
      - build_and_test
      - build_and_push_container:
          requires:
            - build_and_test
          filters:
            branches:
              only: master