# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
orbs:
  gcp-gke: circleci/gcp-gke@0.1.0
  gcr: circleci/gcp-gcr@0.0.2
jobs:
  Build-And-Test:
    description: Build and run the tests
    docker:
      # specify the version
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/rkshkmr800/hotspots
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test ./...
  
  Build-and-Push:
    description: Build the docker images and push to docker registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth

worlflows:
  Continuous-Integration-And-Deployment:
    jobs:
      - Build-And-Test
      - Build-and-Push:
          requires:
            - Build-And-Test
          filers:
            branches:
              only: master

