version: 2.1
# orbs:
#   gcp-gke: circleci/gcp-gke@0.1.0
#   gcr: circleci/gcp-gcr@0.0.2

jobs:
  build_project:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/rkshkmr800/hotspots
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go build ./...

  run_unit_tests:
    description: Build and run the tests
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/rkshkmr800/hotspots
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test ./...
      
workflows:
  cicd:
    jobs:
      - build_project
      - run_unit_tests:
          requires:
            - build_project
      # - build_and_push:
      #     requires:
      #       - test
      #     filers:
      #       branches:
      #         only: master