version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.1.0
  gcr: circleci/gcp-gcr@0.0.2

jobs:
  build_and_test:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/rkshkmr800/hotspots
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go build ./...
      - run: go test ./...

  build_and_push:
    description: Build the image and then push the container
    machine: true
    steps:
      - checkout
      - gcr/auth
      
workflows:
  continuous_integration:
    jobs:
      - build_and_test
      - build_and_push:
          requires:
            - build_and_test
          filers:
            branches:
              only: master