apiVersion: v1
kind: Service
metadata:
  name: backend-hotspots-service
  labels:
    app: hotspots
spec:
  selector:
    app: hotspots-backend-app
  ports:
    - port: 8080
      protocol: TCP
  type: LoadBalancer